[project]
name = "sports-gambling"
version = "0.1.0"
description = "A set of all my scripts related to my gambling fun."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "pandas>=2.3.3",
    "requests>=2.32.5",
]
